<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Platform.Canonical\Platform.Canonical.csproj" />
    <ProjectReference Include="..\Bo.Core\Bo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Platform.Tests" />
  </ItemGroup>

</Project>
